[scene]
width = 800
height = 450

# Fondo
[[acetate]]
id = "bg"
x = 0
y = 0
w = 800
h = 450
fill = "#0b1020"

# Incluye "space" (estrellas)
include = ["src/acetates/space.toml"]

# Panel encima (opcional)
[[acetate]]
id = "panel"
z = 10
x = 80
y = 70
w = 240
h = 120
fill = "#4b14e2"
